### ISSUE TITLE
Add filters in sitemap templates for individual elements

### ISSUE THREAD

**Issue by sareiodata** [wp-seopress/wp-seopress-public#11]
This is needed in order for the TranslatePress plugin to add translations of those url's in the sitemap. 

Created this because I an issue number in order to create a pull request and so we can have a place to discuss the implementation.

**Comment by wp-seopress** [comment]
No problem, if you have questions, let me kow

**Comment by sareiodata** [comment]
@wp-seopress Hi. I don't think I have access to create a pull request / branch. 

I've implemented an initial refactoring for wp-seopress-public/inc/functions/sitemap/template-xml-sitemaps-single.php and will like your feedback before moving forward with the other templates.

**Comment by wp-seopress** [comment]
@sareiodata If you fork the repository, you should be able to make a pull request from this page: https://github.com/wp-seopress/wp-seopress-public/pulls
Let me know if it not the case!

**Comment by wp-seopress** [comment]
I made a quick test and it looks good to me :)

For consistency, the hook names must start with **seopress_sitemaps** instead of **seopress_sitemap**.

When you add comments, can you add something related to TP, eg @credits or @author?

One last thing: remove empty spaces for consistency in the output:

<img width="824" alt="Capture d’écran 2020-02-18 à 17 40 08" src="https://user-images.githubusercontent.com/30056254/74757117-dc5daf80-5275-11ea-84bd-f4bc87346b80.png">

Thank you!

**Comment by sareiodata** [comment]
Great! Will update the pull request with the rest of the files and the changes you suggested!

**Comment by sareiodata** [comment]
Hi, 

The pull request is finalized. Sorry for taking so long. 

The next versions of TranslatePress and SEO Addon will have support for SEOPress.

**Comment by wp-seopress** [comment]
Thanks, I will test this to include it in a future release.
