### ISSUE TITLE
Instant Indexing Settings Keep Resetting

### ISSUE THREAD

**Issue by VR51** [wp-seopress/wp-seopress-public#55]
I have this issue in a number of website on different VPS servers. I keep setting the Instant Indexing feature to On for Bing and Google (with no Google API key set) and I keep refreshing the SEOPress generated Bing API key (I have to keep doing this because the key keeps getting wiped).

Is this an issue I can fix or is this a bug/feature of SEOPress?

Thank you,
Lee

**Comment by wp-seopress** [comment]
Hi,

In order to process your request efficiently, please do not use this Github repository.

If you're a PRO user, use the ticketing system from your customer account https://www.seopress.org/account/your-tickets/.

If not, open a topic on https://wordpress.org/support/plugin/wp-seopress/.

Thank you for understanding.
